### ISSUE TITLE
2D scope shader bug when using NVGs

### ISSUE THREAD

**Issue by PrivatePirate97** [themrdemonized/xray-monolith#101]
When using Beef's NVGs with 2DSS enabled, alt aiming a gun causes the 2D scope shader to stay active.

![Anomaly-1 5 3 Screenshot 2024 11 10 - 00 54 29 90](https://github.com/user-attachments/assets/d3d70fe4-cfc4-4eee-92bb-815b5e0bf5b6)

**Comment by themrdemonized** [comment]
Address the issue to Beef's NVG author, i can't reproduce it
