### ISSUE TITLE
Не работает HDR10

### ISSUE THREAD

**Issue by SVG1** [themrdemonized/xray-monolith#102]
Пробовал его включать даже с полностью удаленной директорией gamedata и кешем шейдеров. После перезапуска игры висит только черный экран. Минут 5 подождал, затем убил процесс. Может нужен монитор с поддержкой данной технологии?
Эх, увидеть бы на скринах или видео как выглядит этот hdr, лучше ли он мода SSS, и стоило ли ради этого жертвовать win7... 
Но как я понял из описания, невозможно сделать захват этого эффекта с помощью программ. Может попробовать сфотографировать?
themrdemonized, если не сложно, не мог бы ты скомпилировать  "AnomalyDX11.exe" и "AnomalyDX11AVX.exe" на старом SDK отдельно, без hdr? "задолбал я уже наверное со своим нытьем:)))" Конечно, у меня установлены 2 системы, и 10 и 7, но сталкер лучше работает под семерку, на ней он раза в полтора меньше тормозит в местах, где производительность падает по вине CPU.  
Например, на локации Бар, если находишься в середине локации, то производительность одинаковая на обеих системах, но находясь на краю локации и повернувшись в сторону бара, торомоза становятся более выражены на десятке, чем на семёрке.

**Comment by themrdemonized** [comment]
нужен монитор и windows 10
