### ISSUE TITLE
The trade menu does not display the weight after the price of the items sold/purchased, as it was in "Clear Sky", "Call of Pripyat", Cop 1.4.22 and 1.5R6

### ISSUE THREAD

**Issue by xXRinzlerrXx** [themrdemonized/xray-monolith#103]
I asked on the website ap.pro unfortunately, there was no solution, maybe you can help, tell me at least which file, script is responsible for this, which lines need to be added
The example in the screenshot
above is the СoP trading window
from the bottom Anomaly 1.5.3

![COP   Anomaly](https://github.com/user-attachments/assets/5d6bd0a2-aa9a-46a5-8e68-38a087807828)

**Comment by themrdemonized** [comment]
Ask Anomaly devs to add that

**Comment by xXRinzlerrXx** [comment]
I thought you were anomaly developers because you are improving the engine, expanding its capabilities

I thought you knew how to add it, or at least the file that is responsible for it.

**Comment by themrdemonized** [comment]
No I'm not Anomaly developer, I'm just a modder.

Anyways, this is not a modded exes issue or engine issue. In Anomaly the inventory UI is fully scripted in ui_inventory.script file. Ask devs or other modders to edit the scripts to add this feature.

**Comment by xXRinzlerrXx** [comment]
Thanks for the tip
