### ISSUE TITLE
frequent crash with reference to "stalker_movement_manager_base.cpp"

### ISSUE THREAD

**Issue by billlcarr** [themrdemonized/xray-monolith#104]
On October 13th I'd opened an issue about a repeatable crash I was having in Garbage. I thought the Respawn Mutants mod was the cause of it and believed it to be solved after removing the mod. But lately I've been having random crashes with similar references in the log. Not sure if it's the same issue, but it looks like it could be. I can't imagine it being a mod I have installed, as I've had the mods I'm currently using for a very long time. Here's a link to the log file and MDMP. Thanks very much for any help you can provide!

https://drive.google.com/drive/folders/1aOESyufU37SHvXyxEUSG5Vut2BPgrdbz?usp=sharing

**Comment by billlcarr** [comment]
I have Beef's NPCs Die in Anomalies. Could this be conflicting with the NPC anomaly evasion behavior in the modded EXEs? I also use Arrival. I wonder if the combination of those mods might be causing this.

**Comment by themrdemonized** [comment]
maybe yes, since enabling the option will alter npc's pathfinding

**Comment by billlcarr** [comment]
Thanks! I'm going to assume that's what it is. Looking at the time this seemed to start happening, it more or less coincides with when I installed Arrival (around a month ago). Started a new game without Arrival (also switched to NPCs die in anomalies improved, as I've read it's a little more stable) to see if it still happens. So far it hasn't. I'm going to go ahead and close this, since it's looking like Arrival + AI die in anomaly was the issue. If it happens again, I'll reopen it.

Thanks so much for your help!
