### ISSUE TITLE
Crash with reference blur2.ppe

### ISSUE THREAD

**Issue by WinteressNavja** [themrdemonized/xray-monolith#105]
My game crashes everytime I get injured or radiated and blur2.ppe should appear. Error message says Expression: : <no expression>/ Function: CPostprocessAnimator::Load/ file: d:\a\xray-monolith\src\xrGame\PostprocessAnimator.cpp/ line: 80/ description: fatal error/ Arguements: Can't find motion file 'blur2.ppe'/ stack trace. I am pretty sure it was caused by this mod as this didn't happen before and I didnt install anything new. How do I fix this, is it possible to fix it?

**Comment by WinteressNavja** [comment]
Stop, never mind, I'm a dummy

**Comment by themrdemonized** [comment]
check your mods
