### ISSUE TITLE
Can you enable access to the *"time_factor function"* from Non-Debug mode?

### ISSUE THREAD

**Issue by specdeler** [themrdemonized/xray-monolith#106]
trying to do a contribution but I posted in wrong section

**Comment by specdeler** [comment]
wrong section sorry is my first time using github

**Comment by themrdemonized** [comment]
Update Anomaly to the latest version, time_factor is available for non debug starting from 1.5.2. 1.5.2 was released 2 years ago, and now we are in 1.5.3
