### ISSUE TITLE
Crash when mounting scope on any weapon

### ISSUE THREAD

**Issue by aorushome** [themrdemonized/xray-monolith#109]
I get a crash with the latest 30.11.24 update when attaching a scope to any weapon.

[14:12:38.996]  
[14:12:38.996] FATAL ERROR
[14:12:38.996]  
[14:12:38.996] [error]Expression    : <no expression>
[14:12:38.996] [error]Function      : CScriptEngine::lua_pcall_failed
[14:12:38.996] [error]File          : D:\a\xray-monolith\xray-monolith\src\xrServerEntities\script_engine.cpp
[14:12:38.996] [error]Line          : 262
[14:12:38.996] [error]Description   : fatal error
[14:12:38.996] [error]Arguments     : 
[14:12:38.996]  1 : [Lua] ...anomaly the zone 1.5.3/bin/..\gamedata\scripts\_g.script(2658) : se_save_var
[14:12:38.996]  
[14:12:38.996] LUA error: ...anomaly the zone 1.5.3/bin/..\gamedata\scripts\_g.script:2658: attempt to index a string value
[14:12:38.996]  
[14:12:38.996] Check log for details
[14:12:38.996]  
[14:12:38.996] 
[14:12:39.000] stack trace:
[14:12:39.000] 
! [14:12:39.000]  [LUA]  0 : [C  ] __newindex
! [14:12:39.000]  [LUA]  1 : [Lua] ...anomaly the zone 1.5.3/bin/..\gamedata\scripts\_g.script(2658) : se_save_var
! [14:12:39.000]  [LUA]  2 : [Lua] ...the zone 1.5.3/bin/..\gamedata\scripts\item_parts.script(629) : copy_parts_con
! [14:12:39.000]  [LUA]  3 : [Lua] ...the zone 1.5.3/bin/..\gamedata\scripts\_g_patches.script(580) : CloneWep
! [14:12:39.000]  [LUA]  4 : [Lua] ...e zone 1.5.3/bin/..\gamedata\scripts\mags_patches.script(323) : CloneWep
! [14:12:39.000]  [LUA]  5 : [Lua] ...5.3/bin/..\gamedata\scripts\zzz_bas_laser_control.script(18) : alife_clone_weapon
! [14:12:39.000]  [LUA]  6 : [Lua] ...he zone 1.5.3/bin/..\gamedata\scripts\item_weapon.script(88) : item_weapon_attach_scope
! [14:12:39.000]  [LUA]  7 : [Lua] ...3/bin/..\gamedata\scripts\aol_mp412_monkeypatches.script(93) : AttachScope
! [14:12:39.000]  [LUA]  8 : [Lua] ...e zone 1.5.3/bin/..\gamedata\scripts\mags_patches.script(338) : attach_scope
! [14:12:39.000]  [LUA]  9 : [Lua] ...he zone 1.5.3/bin/..\gamedata\scripts\item_weapon.script(1002) : func_or_userdata
! [14:12:39.000]  [LUA] 10 : [Lua] ...y the zone 1.5.3/bin/..\gamedata\scripts\axr_main.script(280) : base_make_callback
! [14:12:39.000]  [LUA] 11 : [Lua] ...y the zone 1.5.3/bin/..\gamedata\scripts\a_rax_wd.script(50) : make_callback
! [14:12:39.000]  [LUA] 12 : [Lua] ...anomaly the zone 1.5.3/bin/..\gamedata\scripts\_g.script(118) : SendScriptCallback
! [14:12:39.000]  [LUA] 13 : [Lua] ...gamedata\scripts\zz_ui_inventory_scopes_as_binocs.script(124) : Callback
! [14:12:39.000]  [LUA] 14 : [Lua] ...bin/..\gamedata\scripts\aaa_rax_icon_override_mcm.script(498) : On_Drag
! [14:12:39.000]  [LUA] 15 : [Lua] ...y the zone 1.5.3/bin/..\gamedata\scripts\utils_ui.script(2262) : OnKeyboardBase
! [14:12:39.000]  [LUA] 16 : [Lua] ...3/bin/..\gamedata\scripts\zzz_rax_sortingplus_mcm.script(506) : OnKeyboard
! [14:12:39.000]  [LUA] 17 : [Lua] ...e zone 1.5.3/bin/..\gamedata\scripts\ui_inventory.script(3721) : 
[14:12:39.000]  
[14:12:39.000]

**Comment by themrdemonized** [comment]
Thanks, for now dont use this version, we'll fix it

**Comment by themrdemonized** [comment]
Try the rerelease plz

**Comment by riverkin** [comment]
Can confirm the rerelease works with no crashes when mounting or unmounting scopes, tyty!

**Comment by aorushome** [comment]
working well ty sir.
