### ISSUE TITLE
unequip scope crash stac trace

### ISSUE THREAD

**Issue by viking896** [themrdemonized/xray-monolith#110]
FATAL ERROR
 
[error]Expression    : <no expression>
[error]Function      : CScriptEngine::lua_pcall_failed
[error]File          : D:\a\xray-monolith\xray-monolith\src\xrServerEntities\script_engine.cpp
[error]Line          : 262
[error]Description   : fatal error
[error]Arguments     : 
 1 : [Lua] c:/games/anomaly 1.5.3\gamedata\scripts\_g.script(2659) : se_save_var
 
LUA error: c:/games/anomaly 1.5.3\gamedata\scripts\_g.script:2659: attempt to index a string value
 
Check log for details
 

stack trace:

! [LUA]  0 : [C  ] __newindex
! [LUA]  1 : [Lua] c:/games/anomaly 1.5.3\gamedata\scripts\_g.script(2659) : se_save_var
! [LUA]  2 : [Lua] c:/games/anomaly 1.5.3\gamedata\scripts\item_parts.script(629) : copy_parts_con
! [LUA]  3 : [Lua] c:/games/anomaly 1.5.3\gamedata\scripts\_g_patches.script(580) : alife_clone_weapon
! [LUA]  4 : [Lua] c:/games/anomaly 1.5.3\gamedata\scripts\item_weapon.script(124) : detach_scope
! [LUA]  5 : [Lua] c:/games/anomaly 1.5.3\gamedata\scripts\utils_item.script(511) : detach_addon
! [LUA]  6 : [Lua] c:/games/anomaly 1.5.3\gamedata\scripts\ui_inventory.script(1373) : 
! [LUA]  7 : [Lua] c:/games/anomaly 1.5.3\gamedata\scripts\utils_ui.script(3311) :

**Comment by themrdemonized** [comment]
its fixed
