### ISSUE TITLE
Game freez on inventory or stash opening in the new Stalker GAMMA 0.9.3 version. 

### ISSUE THREAD

**Issue by Krushx0** [themrdemonized/xray-monolith#111]
After a fresh GAMMA installation with the latest Gamma Launcher 6.7.0.0 and updated 0.9.3 game version and both the STALKER-Anomaly-modded-exes_2024.11.30.zip and STALKER-Anomaly-modded-exes_DX11-AVX_pdb.zip have been extracted to the same place as before produce a game freez when I open the inventory or open a stash. In the latest version of GAMMA inventory have been modified.
Running on windows 10 with the DX11-AVX version of the modded exe. 
Nvidia card: GTX 1070
CPU: Intel 13600k

**Comment by themrdemonized** [comment]
Does it freeze with previous versions of exes?

**Comment by Krushx0** [comment]
I just tested now with the 2024.11.27 version, the game running and the inventory and stash can be open, but I did not tested any mod that require the modded exes in any shape or form.
Just for sanity sake I tested again with the new 2024.11.30 version and its reproduce the same undesired result with the game freezes when you open the inventory or stash.
It looks like the new version has some issues.

**Comment by themrdemonized** [comment]
I could reproduce the issue when i had stale files in gamedata folder, they can cause problems. Modded exes moved all files to .db archive months ago, you shouldn't have any scripts and other stale files in gamedata. You need to do a clean reinstall of exes.

How to do clean reinstall: https://github.com/themrdemonized/xray-monolith?tab=readme-ov-file#troubleshooting

**Comment by Krushx0** [comment]
First I thought: 
you might missed it, but I started the whole thread with the "After a fresh GAMMA installation" so stale files impossible to have since that was months ago before the new GAMMA release with gamedata folder included in the modded exes zip folder according to you and the pictures on the GitHub page with the "Read the instructions PLEASE!!!" section, which implies that this could not be an issue.
But then I tested it with your troubleshooting instruction link anyway and deleted all the files and folders except the ones that it mentioned(btw I did not have a localization.ltx in gamedata/configs) and with the new 2024.11.30 and it worked.
Which means that with fresh install of Anomaly 1.5.3 there are some default files that cause issues and with the troubleshooting guide it can be fixed.
It looks like the default installation guide need to be updated with the troubleshooting guide steps to be correct. 
Thx for pointing me to the right direction. I did not think that with everything freshly installed I need to do additional steps apart from the installation instructions.

**Comment by themrdemonized** [comment]
There will be no problems with clean anomaly install, because it doesnt have anything in gamedata. I also dont support modpacks, so any changes you do is on your own.
