### ISSUE TITLE
SSS water reflections aren't working properly

### ISSUE THREAD

**Issue by billlcarr** [themrdemonized/xray-monolith#113]
SSS 22 water reflections aren't working properly with the 2024.12.09 binaries. This problem isn't present in the binaries packaged with SSS 22.

![waterreflections](https://github.com/user-attachments/assets/57e9451f-8be3-4a6d-baad-b98ac9a91b3b)

**Comment by themrdemonized** [comment]
Please try the rerelease, it will be ready in 30 minutes

**Comment by billlcarr** [comment]
That fixed it. Thanks so much!
