### ISSUE TITLE
Fail to detach scope from some weapons

### ISSUE THREAD

**Issue by UcancalmeBerlin** [themrdemonized/xray-monolith#114]
I found that if I detach scope from some weapons, such as mosin, sks and 98k, and when zooming in, instead of the ironsight the scope will show up while zoom factor decreased compared to when scope is attached. I test it with vanilla 1.5.3. This seems to happen as long as I install the modified exes. 
I'm not sure if this is just because I install it wrongly or other problems?

**Comment by themrdemonized** [comment]
Please check the latest version, see if its fixed

**Comment by UcancalmeBerlin** [comment]
It's fixed, thanks a lot!
