### ISSUE TITLE
Error on engine launch dx10HW

### ISSUE THREAD

**Issue by RossBarnie** [themrdemonized/xray-monolith#116]
Hello, I'm running into the following error. I'm running this on Wine on Linux so I appreciate this is probably something you wouldn't run into normally. I'm able to run the vanilla exe fine. I'm running with Mod Organizer 2 with:
- Beefs NVGs
- MCM
- Enhanced Shaders and Color Grading
- Screen Space Shaders
- Atmospherics

Whenever I start the game I get the following:

```
...
Starting RENDER device...
* GPU [vendor:10DE]-[device:1B06]: NVIDIA GeForce GTX 1080 Ti
 
FATAL ERROR
 
[error]Expression    : m_pSwapChain->QueryInterface(&swapchain3)
[error]Function      : CHW::CreateDevice
[error]File          : F:\ANOMALY BUILDS\xray-1.5.3 - 2024.11.30\xray-monolith\src\Layers\xrRenderDX10\dx10HW.cpp
[error]Line          : 483
[error]Description   : 
 

stack trace:

 

SymInit: Symbol-SearchPath: '.;Z:\mnt\10646aff-9b90-430a-9c38-bff17afab8c0\SteamLibrary\StalkerAnomaly\Anomaly-1.5.3-Full.2;Z:\mnt\10646aff-9b90-430a-9c38-bff17afab8c0\SteamLibrary\StalkerAnomaly\Anomaly-1.5.3-Full.2\bin;C:\windows;C:\windows\system32;', symOptions: 530, UserName: 'steamuser'
OS-Version: 6.2.9200 () 0x0-0x1
Z:\mnt\10646aff-9b90-430a-9c38-bff17afab8c0\SteamLibrary\StalkerAnomaly\Anomaly-1.5.3-Full.2\bin\AnomalyDX11AVX.exe:AnomalyDX11AVX.exe (0000000140000000), size: 16433152 (result: 0), SymType: '-exported-', PDB: 'Z:\mnt\10646aff-9b90-430a-9c38-bff17afab8c0\SteamLibrary\StalkerAnomaly\Anomaly-1.5.3-Full.2\bin\AnomalyDX11AVX.exe'
```

I had a look at the reported line but I couldn't make much sense of it. Any help appreciated.

**Comment by themrdemonized** [comment]
this is not modded exes build, i can't help with that.
But by the looks of it, there is a problem with dxgi swapchain on linux.

**Comment by RossBarnie** [comment]
Thanks to your comment I noticed I hadn't installed `dxvk` which has fixed the issue.
