### ISSUE TITLE
grok_bo.script call back scripts not working.

### ISSUE THREAD

**Issue by gitTerebi** [themrdemonized/xray-monolith#15]
With gamma modpack installed, the grok_bo.script isn't firing the npc_on_before_hit lua method.
![image](https://github.com/themrdemonized/xray-monolith/assets/12906211/3dcafe75-b55e-4aa0-9784-954f509a17d4)

You can fire weapon and no hits are registered, however knife hits do work.

Specifically this mod in the list 'G.A.M.M.A. Close Quarter Combat' when you disable it, hits work again.
![image](https://github.com/themrdemonized/xray-monolith/assets/12906211/4bf50fbc-19ce-433a-8bf4-6813333270c6)

If you edit script and rename method to npc_on_before_hit_anything, it does work.

Script looks like this:
![image](https://github.com/themrdemonized/xray-monolith/assets/12906211/0b2f05b6-8255-4862-8fe5-95f49b934b0f)

**Comment by themrdemonized** [comment]
ask grok to fix it
