### ISSUE TITLE
Why does the script engine call the garbage collector twice in a row?

### ISSUE THREAD

**Issue by MagielBruntink** [themrdemonized/xray-monolith#19]
https://github.com/themrdemonized/xray-monolith/blob/bc49d5e66992c410962b2a6ed5ef7c0e04d9a598/src/xrServerEntities/script_engine.cpp#L601
https://github.com/themrdemonized/xray-monolith/blob/bc49d5e66992c410962b2a6ed5ef7c0e04d9a598/src/xrServerEntities/script_engine.cpp#L602

**Comment by themrdemonized** [comment]
primary reason is this: https://stackoverflow.com/questions/28320213/why-do-we-need-to-call-luas-collectgarbage-twice

Whether or not is it important - idk

**Comment by MagielBruntink** [comment]
I have been experimenting a bit with luajit GC settings and finding `lua_gcstep 1000` set in console to produce somewhat less stutters.

First I moved
https://github.com/themrdemonized/xray-monolith/blob/bc49d5e66992c410962b2a6ed5ef7c0e04d9a598/src/xrGame/console_commands.cpp#L2253C2-L2253C2 

out of the DEBUG ifdef and rebuilt. Not sure if it's really much better; there may be other side effects.

**Comment by themrdemonized** [comment]
You can make a pull request with edits
