### ISSUE TITLE
Occasional crashes "pure virtual function call"

### ISSUE THREAD

**Issue by MagielBruntink** [themrdemonized/xray-monolith#21]
Having occasional (once every ~2 hours) crashes with following error log:
<img width="550" alt="image" src="https://github.com/themrdemonized/xray-monolith/assets/3635696/e17cb836-c8bb-4348-9a17-8c650032d6f0">

Occasions:
 - loading new level (2-3 times)
 - after emission ended (1 time)

Full log:
[20240118-xray_magiel.log](https://github.com/themrdemonized/xray-monolith/files/13981749/20240118-xray_magiel.log)

**Comment by MagielBruntink** [comment]
I wonder why this `debug_on_thread_spawn` call is here: https://github.com/themrdemonized/xray-monolith/blob/d0e127cbfd98842d03acafe3e89e9328f999468a/src/xrCore/_math.cpp#L310

Seems to me this will always crash right at the start of `_initialize_cpu_thread()` in `_math.cpp`. 

`debug_on_thread_spawn` is the only source of "pure virtual function call" fatal errors as far as I can see (grep). It is the only code that uses the `pure_call_handler` that ultimately generates this error.

Perhaps we could try removing the call to `debug_on_thread_spawn`?

**Comment by themrdemonized** [comment]
debug functions have nothing to do with that. this error can raise because of faulty mods or bad interactions between Lua and engine side. You can read more in _g.script

**Comment by MagielBruntink** [comment]
But this call to `debug_on_thread_spawn` is active whether the user starts in debug mode or not.

In `_math.cpp`
<img width="376" alt="image" src="https://github.com/themrdemonized/xray-monolith/assets/3635696/445987eb-4f75-4cb5-b84c-184f9d60a36a">

Calling that function will crash the game:

In `xrDebugNew.cpp`
<img width="504" alt="image" src="https://github.com/themrdemonized/xray-monolith/assets/3635696/c328e28a-156a-4227-8c5e-82fb8f073256">
