### ISSUE TITLE
How to contribute / dev guide

### ISSUE THREAD

**Issue by ChristopherCapito** [themrdemonized/xray-monolith#58]
Hi there. I was looking for a place to learn how to contribute to the project. I am trying to get familiar with the engine to try some modifications and if possible contribute.

I see there are not many open issues, though there surely are bugs and improvements to be made. Is there a project overview somewhere, or a discord? I was looking at OpenXray as well but that seems to not be used at all by the larger modding community, as most is based on Anomaly now it seems. Is that a correct assessment? Just trying to figure out how to best contribute :)

**Comment by themrdemonized** [comment]
Official discord: https://discord.com/invite/c4RuJNs
Contribution is as usual: fork the project, do things and make a pull request.
I can't give comprehensive overview since i'm not the original developer, it would be too much work. You can visit discord and ask for help for certain things
