### ISSUE TITLE
DXML module not found in compiled engine

### ISSUE THREAD

**Issue by MiS-SP** [themrdemonized/xray-monolith#60]
Hi after multiple attempts to compile DX11-AVX solution I get this error:
![image](https://github.com/user-attachments/assets/6e1d59d7-7531-4fe6-821e-6526042acb28)
I just copy the finished exe file from the _build\_game\bin_dbg folder.
Can you help me?

**Comment by themrdemonized** [comment]
you need files from gamedata folder
