### ISSUE TITLE
Крупное падение ФПС из-за SSS'овского считывания маски худа

### ISSUE THREAD

**Issue by MrFlashMode** [themrdemonized/xray-monolith#68]
Данная репозитория модифицированных экзешников предполагает свою работу на любом рендере и вне зависимости от наличия установленного Screen Space Shaders. следовательно это очень существенная проблема

Заключается она в том, что начиная с SSS 21 движок считывает маску худа (любого предмета в руках), и при игре БЕЗ Screen Space шейдеров, каждая проведённая секунда в игре с предметом в руках постепенно понижает общую кадровую частоту, но в тоже время при убирании предмета кадры возвращаются. 

По всей видимости, движок пытается считать маску, но из-за отсутствия SSS шейдера даёт сбой и повторяет данный цикл постоянно, что понижает общую производительность.

Для воспроизведения проблемы необходимо:
- Включить любой мониторинг ресурсов, чтобы отобразить кадровую частоту
- Запустить ванильную игру (DX11 без SSS шейдеров), но с последними модифицированными экзешниками
- Взять в руки любой предмет (пистолет, болт, детектор, абсолютно не важно)
- Просто стоять с предметом в руках, и наблюдать как со временем понижается кадровая частота

P.S.: В моём случае:
- Я загрузился в тест-руму с 490фпс,
- Взял в руки пистолет и простоял 4 минут 32 секунды на месте
- Кадровая частота упала вплоть до 60 кадров, 
- После чего я убрал пистолет и кадры вернулись до 490фпс
- Последующее повторное доставание пистолета опускало кадры до 60 (и ниже, зависит от того, сколько простоять), а при убирании снова возвращало до 490

**Comment by themrdemonized** [comment]
Ждём фикс от автора sss
