### ISSUE TITLE
feature request: add option to force all addons to be shown only on English in MCM addon list

### ISSUE THREAD

**Issue by BlackburnUTG** [themrdemonized/xray-monolith#77]
I play on Russian language, and I so tired that in MCM menu some addons have russian localization, and some are on English only. Because of that I spent a lot of time trying to find right addon in the mcm list.

Can we have a feature that force all addons to be shown only on English, no mater what language in game settings is used?

**Comment by themrdemonized** [comment]
its impossible to make it specifically only for mcm addons. Translate English addons into Russian
