### ISSUE TITLE
Grenade launcher rounds issue when loading save

### ISSUE THREAD

**Issue by Grokitach** [themrdemonized/xray-monolith#79]
It seems that since Anomaly 1.5.3 update there's an issue with grenade launcher rounds:

Reloading a save or moving between maps while having the UBGL active on a gun transfers the amount of ammo the gun had loaded in the main magazine to the UBGL (UBGL can thus have 30 rounds after reloading a save).

Shooting and pressing V twice lets you shoot again until you run out of ammo.

Detaching the UBGL or unloading the gun returns all grenades to your inventory.

**Comment by themrdemonized** [comment]
try the latest version please

**Comment by Grokitach** [comment]
According to my testers it works. Thanks for the quick fix 😃
