### ISSUE TITLE
Не работают псевдо 3D прицелы.

### ISSUE THREAD

**Issue by OneMorePseudoCoder** [themrdemonized/xray-monolith#82]
Не работает этот мод на версии от 6-ого числа (от 7-ого не проверял): https://www.moddb.com/mods/stalker-anomaly/addons/shader-3d-scopes
На пятой версии вся прекрасно и дело не в шейдерах, а в двигле. Пробовал гейм дату от релиза 5-ого дня с бинарниками 6-ого, всё равно не работало.

**Comment by themrdemonized** [comment]
fixed in 2024.10.07
