### ISSUE TITLE
CTD when loading save

### ISSUE THREAD

**Issue by billlcarr** [themrdemonized/xray-monolith#84]
I have a weird issue where the game crashes to desktop just before the "Click to continue" text pops up when loading my most recent save. Earlier saves made in the same area work fine, so it's not a big problem, but I was wondering if you could look at the log and MDMP when you have time (all I can see in the MDMP is a generic memory access violation "c0000005", but nothing that gives me any clue as to what caused it). I'd just like to know if this is just a random glitch, or a symptom of an actual problem I need to remedy. I'm using the executables that come with the current SSS 22 alpha (which I believe is based on the 9/23/2024 modded EXEs). Here's a link to the log and mdmp. Thanks very much!

https://drive.google.com/drive/folders/1xgwf7zoa8apEyHAB8PQe0wly3dVzeE7G?usp=sharing

**Comment by themrdemonized** [comment]
I can't help you if you use other exes, send the issue to sss author

**Comment by billlcarr** [comment]
Was able to reproduce the crash using the 24.10.10 modded EXEs. Here's the log and MDMP:

https://drive.google.com/drive/folders/13NuCbrr07Gt_kssUNfA8F6AK0UjduYdK?usp=sharing
