### ISSUE TITLE
Repeatable crash in Garbage

### ISSUE THREAD

**Issue by billlcarr** [themrdemonized/xray-monolith#87]
Using the 24.10.10 binaries I'm getting a repeating crash to desktop once I reach a certain area in Garbage (and this is on a brand new playthrough on a fresh 1.5.3 install with all mods updated where necessary). I'm guessing it's probably a mod that's causing it, but based on the log file and MDMP, I can't tell if that's the case (and definitely can't tell which mod it might be).

The log file and MDMP are here-

https://drive.google.com/drive/folders/1xgwf7zoa8apEyHAB8PQe0wly3dVzeE7G?usp=sharing

Thanks very much!

**Comment by themrdemonized** [comment]
Try version https://github.com/themrdemonized/xray-monolith/releases/tag/2024.10.5 and see if it still crashes

**Comment by billlcarr** [comment]
Thanks!

This is weird. With 24.10.10 it crashed after a few minutes of playing 4 times in a row. After that it stopped crashing, so it seems kind of random now. Tried it with 24.10.5 and didn't get a crash, but I don't know whether this is random chance or not...

To give more detail, after the 4th crash in a row, I looked through the game files and found that I had a mod installed that modifies "wpn_hand_val_hud_animation.omf", which is updated in 1.5.3. So I removed that file, ran a few tests and it seemed like the crashing stopped. I thought that was the fix, but to further test, I put that file back, and still no crash. So still seems random.

Anyway, will keep testing for a few hours with 24.10.5 and post back here whether I eventually get a crash or not.

Did the log or MDMP give you any idea what might be the cause?

Thanks very much for your time!

**Comment by themrdemonized** [comment]
Yea, it is something with the map nodes and monsters pathfinding. Map related stuff was updated recently.

**Comment by billlcarr** [comment]
Thanks for the info! Did a little more testing with 24.10.10 and was finally able to reproduce the crash.

Testing now with 24.10.5 again, will let you know what happens, but so far no crash.

**Comment by billlcarr** [comment]
Well damn, took a little while, but got the same crash with 24.10.5

Here's the log and mdmp-

https://drive.google.com/drive/folders/13NuCbrr07Gt_kssUNfA8F6AK0UjduYdK?usp=sharing

**Comment by billlcarr** [comment]
I had posted about a crash a few days ago that happened while testing out SSS 22 alpha, which used 24.9.23 modified with new SSS code. I was able to repeat the crash with 24.10.10 earlier today. Looking at the log now, the logs aren't identical, but they both mention pathing in the error message. Just wondering if this might have been caused by the same problem. Here's the log and mdmp from that crash if it helps-

https://drive.google.com/drive/folders/1xgwf7zoa8apEyHAB8PQe0wly3dVzeE7G?usp=sharing

**Comment by themrdemonized** [comment]
yea the error is the same as in 2024.10.10 version, so i guess some monster cant move correctly on the map

**Comment by billlcarr** [comment]
Thanks! Do you know if this is caused by something in the modded EXEs, or an add-on? I recently installed the Re:Spawn Mutant Collection, and the saves that this happens on were created while it was installed, but the crash also happens with it deactivated. So I guess I'm wondering if whatever is causing this might be from that add-on and it's getting baked into the save.

Also, don't know if this helps, but with the earlier save, the one that crashes at the loading screen, I'm sometimes able to load the save without it crashing right away. When that happens, if I make a new save, that new save doesn't crash. This happens with and without Re:Spawn installed.

**Comment by themrdemonized** [comment]
its most likely caused by addons

**Comment by billlcarr** [comment]
Thanks! I forgot to mention, I was also able to reproduce the crash on the version of the modded EXEs that came with SSS 21, which used 24.8.10. So I think it's definitely something getting baked into the save. I'm going to start a new save with the latest EXEs, but without ReSpawn installed and see how it goes.  Since it's most likely caused by an add-on, I'll go ahead and close this thread and report it as a possible problem to that mod author. If it happens again on a new game without ReSpawn, I'll report back here.

Thanks very much for your time and help! I really appreciate it!
