### ISSUE TITLE
cform_cache?

### ISSUE THREAD

**Issue by I-Am-Everyday-People** [themrdemonized/xray-monolith#88]
Using 7/10 and 14/10 releases creates cform_cache folder in appdata, which can become quite large with cached files reaching up to 200MB per level. Before deletion my cform_cache folder contained 2.98GB.

This cache is not created when using 1/10 release. I'm aware that this feature is supposed to decrease load times, is this intended/necessary for these newer versions, can it be toggled/disabled?

**Comment by themrdemonized** [comment]
Yes its necessary due to new method of caching levels for reducing loading times. Maybe it can be optional later

**Comment by I-Am-Everyday-People** [comment]
OK, thanks for the reply.
