### ISSUE TITLE
Shader crash with yuv2rgb.ps

### ISSUE THREAD

**Issue by billlcarr** [themrdemonized/xray-monolith#89]
Using the 24.10.10 EXEs I'm getting a CTD quite often with this in the log-

! PS:  g:/games/stalker - anomaly\appdata\shaders_cache\r4\yuv2rgb.ps\2048111100110000000000100000111221114110280121621000000
! CreatePixelShader hr == 0x887a0005
! PS:  g:/games/stalker - anomaly\appdata\shaders_cache\r4\yuv2rgb.ps\2048111100110000000000100000111221114110280121621000000
! CreatePixelShader hr == 0x887a0005

The full log is here-

https://drive.google.com/file/d/1H6Y6_0w2tEe5WZu2jIVT68jn5uDChsFr/view?usp=sharing

Thanks!

**Comment by billlcarr** [comment]
To give more detail, when this happens, I'm able to fix it by clearing the shader cache, but it usually takes 4 or 5 times (load game with "Delete Shader Cache" selected, load save, get another CTD with that error in the log, repeat until I finally stop getting the CTD). The game will then run fine for 3 or 4 days, but it will eventually happen again. The last time it happened was 4 days ago with the binaries that came with SSS 22 Alpha (which were based on 24.9.23). It happened today, with the exact same behavior, using the 24.10.10 binaries. Going through the same process, I was able to get it to stop crashing, and have now updated to the 24.10.14 binaries. Just wondering what would cause this to keep occurring.

**Comment by themrdemonized** [comment]
The log mentions wallmarks, maybe they are failed to render, and shader receives no data but still tries to render

**Comment by billlcarr** [comment]
Thanks for the response. I've been getting that message in the log for a long time. Could it be a mod? The only one I have that affects wallmarks is "Impact Decals", which is just textures.

I'll try running with that disabled and see if I still get that message in the log. I'll let you know what happens.

Thanks again!

**Comment by billlcarr** [comment]
I know this is closed, but I just wanted to thank you for your help. Was able to find the mod that was causing those messages in the log, and without your help I wouldn't have even thought to look for it. So thank you very much!
