### ISSUE TITLE
Отрицательный FOV в оптике.

### ISSUE THREAD

**Issue by SVG1** [themrdemonized/xray-monolith#90]
Исправьте пожалуйста отрицательный FOV, выставляющийся при первом включении оптического прицела, после загрузки сохранения. Раньше было нормально, по умолчанию было увеличение на 1 шаг.  Конечно, любое движение колеса мыши исправляет это, сбрасывая увеличение на 0, но напрягает каждый раз после загрузки сохранения сбрасывать увеличение прицела, особенно, когда нужно без промедления применять оружие. Я играю с FOV = 60, который был в классическом Сталкере, а не с тем углом обзора, что по умолчанию - может в этом проблема? И ещё, может поможет: все галочки касательно  оптического прицела у меня включены в настройках "Modded Exes". Шаг увеличения в оптике = 10.

**Comment by themrdemonized** [comment]
попробуй последнюю версию

**Comment by SVG1** [comment]
Теперь всё хорошо, спасибо !

**Comment by SVG1** [comment]
Теперь всё хорошо, спасибо !
