### ISSUE TITLE
Точка входа в процедуру createdxgifactory2 не найдена в библиотеке dll dxgi.dll

### ISSUE THREAD

**Issue by SVG1** [themrdemonized/xray-monolith#92]
Вот такая шляпа появляется при запуске на Win7 DX11.
Полагаю, эта ошибка появилась из-за введения  HDR10. Можно ли как-то изолировать код HDR10 для тех, кто не использует эту фичу? И чтобы только после включения самой функции в настройках, она требует перезапустить игру и тогда уже нужна Win10 или выше, а на семёрке не будет запускаться.

**Comment by themrdemonized** [comment]
На данный момент нельзя
