### ISSUE TITLE
Равномерный шаг увеличния оптического прицела.

### ISSUE THREAD

**Issue by SVG1** [themrdemonized/xray-monolith#98]
Можно ли сделать так, чтобы увеличение было одинаковым с каждым шагом, а не так, как сейчас, когда вначале шаг увеличния маленький, но с каждым разом он всё больше? Десятый же шаг вообще грубый. Из-за этого тяжело спрогнозировать нужное масштабирование. А пока дёргаешь колёсико туда-сюда, тебя уже подстрелят :(

**Comment by themrdemonized** [comment]
Шаг увеличения равномерен, FOV меняется на фиксированное значение. Просто есть разница когда FOV в одном случае меняется с 50 до 55, а в другом с 5 до 10. Посмотрю позже

**Comment by themrdemonized** [comment]
попробуй последнюю версию, введи в консоли `new_zoom_delta_algorithm 1`

**Comment by SVG1** [comment]
Попробовал, стало в разы лучше! Но равномерное увеличение видно только на прицелах со средним максимальным увеличением, таких как leupold или March... из мода BaS. Но на оружии с большим зумом, таких как remington m700 с патроном lapua magnum заметно, что с каждым увеличением шаг становится меньше, как если бы новый алгоритм "перевернул" старый алгоритм наоборот. Но всё-равно, новый алгоритм меня более чем устраивает, так что, если нет желания дальше что-то менять, то и не надо. Единственное, что нужно пофиксить, это включение этой фичи через меню, короче она не включается в меню "Modded exes", только через консоль.

**Comment by themrdemonized** [comment]
Ok, пофикшу
