### ISSUE TITLE
Why Windows 10 1903 at least required?

### ISSUE THREAD

**Issue by kda2495** [themrdemonized/xray-monolith#99]
This modded exes working well on Windows 7 SP1 with the latest Visual C++ Redistributables (2022 also).

**Comment by SVG1** [comment]
Only launching on DX11 requires Windows 10, the rest of the APIs work on Win7.

**Comment by themrdemonized** [comment]
Exactly

**Comment by Maksim2703** [comment]
Пожалуйста верните dx11 как он был когда-то, у меня он перестал запускаться после обновления с ошибкой API DLL, у меня виндоус 7, как я понял вы перевели его на 10 виндоус, но зачем? Дайте нормально играть, это уже чересчур так ограничивать.
